name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload Release Binaries
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mv target/${{ matrix.target }}/release/s3fs target/${{ matrix.target }}/release/s3fs_${{ matrix.target }}
          gh release upload ${{github.event.release.tag_name}} target/${{ matrix.target }}/release/s3fs_${{ matrix.target }}
